# Generated by Django 5.0.6 on 2024-07-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_chathistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
