# Generated by Django 5.0.6 on 2024-07-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_chathistory_recommendations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
